services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer # Do not change
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # Do not change
      - /var/run/docker.sock:/var/run/docker.sock:ro # Do not change
    depends_on:
      - caddy
    ports:
      - 8080:8080
    environment:
      SKIP_DOMAIN_VALIDATION: 'true'
      # AIO_DISABLE_BACKUP_SECTION: false # Setting this to true allows to hide the backup section in the AIO interface. See https://github.com/nextcloud/all-in-one#how-to-disable-the-backup-section
      APACHE_PORT: 11000 # Is needed for reverse proxy
      APACHE_IP_BINDING: 127.0.0.1 # Set for Caddy
      APACHE_ADDITIONAL_NETWORK: aio_bridge # (Optional) Connect the apache container to an additional docker network. Needed when behind a web server or reverse proxy running in a different docker network on the same server. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6 # Allows to adjust borgs retention policy. See https://github.com/nextcloud/all-in-one#how-to-adjust-borgs-retention-policy
      NEXTCLOUD_DATADIR: /home/zach/aio/data # Do not change after initialization
      NEXTCLOUD_MAX_TIME: 3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      NEXTCLOUD_ADDITIONAL_APKS: imagemagick # allows additional packages permanently.
      NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick # allows additional php extensions permanently.

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # Do not change

networks:
  merged_aio_bridge:
    name: merged_aio_bridge
    external: true
